// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UToV4NsevMWoiEVhDCXbVR3z-EvwMsc',
    appId: '1:294339597264:web:65c7f1b34e299d63c15fd5',
    messagingSenderId: '294339597264',
    projectId: 'meettenants',
    authDomain: 'meettenants.firebaseapp.com',
    storageBucket: 'meettenants.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx1GBt7nrLRIL5dxgijwrOnH6w0ZLx7U0',
    appId: '1:294339597264:android:ca2b92365c7131d4c15fd5',
    messagingSenderId: '294339597264',
    projectId: 'meettenants',
    storageBucket: 'meettenants.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpBPg-CxzYMR2WWQ7HGK95lrr3sAOhtfE',
    appId: '1:294339597264:ios:6cd90ba07681018dc15fd5',
    messagingSenderId: '294339597264',
    projectId: 'meettenants',
    storageBucket: 'meettenants.appspot.com',
    iosBundleId: 'com.example.meettenants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpBPg-CxzYMR2WWQ7HGK95lrr3sAOhtfE',
    appId: '1:294339597264:ios:6cd90ba07681018dc15fd5',
    messagingSenderId: '294339597264',
    projectId: 'meettenants',
    storageBucket: 'meettenants.appspot.com',
    iosBundleId: 'com.example.meettenants',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5UToV4NsevMWoiEVhDCXbVR3z-EvwMsc',
    appId: '1:294339597264:web:8a5f0d14b45540ccc15fd5',
    messagingSenderId: '294339597264',
    projectId: 'meettenants',
    authDomain: 'meettenants.firebaseapp.com',
    storageBucket: 'meettenants.appspot.com',
  );
}
